"""Add blood_bank module(corrected version)

Revision ID: 55901ff66469
Revises: affc7e032f32
Create Date: 2026-08-11 16:07:49.103586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55901ff66469'
down_revision: Union[str, Sequence[str], None] = 'affc7e032f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood_group')
    )
    op.create_index(op.f('ix_blood_inventory_id'), 'blood_inventory', ['id'], unique=False)
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units_requested', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_id'), 'blood_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blood_requests_id'), table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_index(op.f('ix_blood_inventory_id'), table_name='blood_inventory')
    op.drop_table('blood_inventory')
    # ### end Alembic commands ###
